// Generated by https://quicktype.io

export interface GeneralGenreManga {
  data: generalDatumManga[];
}

export interface generalDatumManga {
  mal_id: number;
  name:   string;
  url:    string;
  count:  number;
}
