// Generated by https://quicktype.io

export interface Episodes {
  data: DataEpisode;
}

export interface DataEpisode {
  promo:        Promo[];
  episodes:     Episode[];
  music_videos: any[];
}

export interface Episode {
  mal_id:  number;
  title:   string;
  episode: string;
  url:     string;
  images:  EpisodeImages;
}

export interface EpisodeImages {
  jpg: Jpg;
}

export interface Jpg {
  image_url: null;
}

export interface Promo {
  title:   string;
  trailer: Trailer;
}

export interface Trailer {
  youtube_id: string;
  url:        string;
  embed_url:  string;
  images:     TrailerImages;
}

export interface TrailerImages {
  image_url:         string;
  small_image_url:   string;
  medium_image_url:  string;
  large_image_url:   string;
  maximum_image_url: string;
}
