// Generated by https://quicktype.io

export interface Product {
  id:          number;
  name:        string;
  description: string;
  price:       string;
  image:       string;
  category_id: number;
}
