// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface Product {
  Id:           number;
  Name:         string;
  Description:  string;
  Price:        string;
  RegularPrice: string;
  CategoryIds:  string;
  Tags:         string;
  Color:        string;
  Material:     string;
  Images:       string;
  IsFeatured:   number;
  IsNew:        number;
  IsPopular:    number;
  RelatedIds:   string;
}
