// Generated by https://quicktype.io

export interface Authten {
  msj:     string;
  data:    Data;
  errores: any[];
}

export interface Data {
  token: string;
  login: Login;
}

export interface Login {
  usuariologin: string;
}
