// Generated by https://quicktype.io

export interface UsuariosByID {
  msj:     string;
  data:    DatumLoginUsuarios[];
  errores: any[];
}

export interface DatumLoginUsuarios{
  idlogin:         number;
  usuariologin:    string;
  contrasenalogin: string;
  correologin:     string;
  codigo:          string;
  fallido:         number;
  estado:          string;
  createdAt:       string;
  updatedAt:       string;
}
