// Generated by https://quicktype.io

export interface Cargos {
  msj:     string;
  data:    DatumCargos[];
  errores: any[];
}

export interface DatumCargos {
  idcargo:          number;
  descripcionCargo: string;
}


