// Generated by https://quicktype.io

export interface Contratos {
  msj:     string;
  data:    DatumCon[];
  errores: any[];
}

export interface DatumCon {
  idcontrato:   number;
  tipocontrato: string;
}
