// Generated by https://quicktype.io

export interface Direccion {
  msj:     string;
  data:    DatumDirec[];
  errores: any[];
}

export interface DatumDirec {
  id:      number;
  sector:  string;
  colonia: string;
  calle:   string;
  avenida: string;
  numcasa: number;
}
