// Generated by https://quicktype.io

export interface Empleados {
  edad:           number;
  idempleado:     number;
  identidad:      string;
  nombrecompleto: string;
  correo:         string;
  genero:         string;
  estcivil:       string;
  telefono:       string;
  tiposangre:     string;
  fechanac:       string;
  departamento:   string;
  imagen:         string;
  idusuario:      number;
  iddireccion:    number;
  idcargo:        number;
  idcontrato:     number;
}
