// Generated by https://quicktype.io

// export interface Empleado {

// data: EmpleadoList[];

// }


export interface EmpleadoList {
  edad:           number;
  idempleado:     number;
  identidad:      string;
  nombrecompleto: string;
  correo:         string;
  genero:         genero;
  estcivil:       string;
  telefono:       string;
  tiposangre:     string;
  fechanac:       string;
  departamento:   string;
  imagen:         null;
  idusuario:      number;
  iddireccion:    number;
  idcargo:        number;
  idcontrato:     number | null;
}


export enum genero{
Masculino='Masculino',
Femenino='Femenino'
}

export enum estadocivil{
Casado='Casado',
Divorciado='Divorciado',
Soltero='Soltero',
Viudo='Viudo'

}
