// Generated by https://quicktype.io

export interface Gerencias {
  msj:     string;
  data:    DataGerencia[];
  errores: any[];
}

export interface DataGerencia {
  idgerencia:  number;
  descripcion: string;
  gerente:     string;
}
