// Generated by https://quicktype.io

export interface Listempleados {
  msj:     string;
  data:    Data;
  errores: any[];
}

export interface Data {
  modulo:      string;
  descripcion: string;
  rutas:       Ruta[];
}

export interface Ruta {
  ruta:        string;
  descripcion: string;
  metodo:      string;
  parametros:  string;
}
